name: base image
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: quay.io/buildah/stable
      options:
        --security-opt seccomp=unconfined
    steps: 
    - uses: actions/checkout@v2
    - run: ./script.sh
    - run: buildah images
