name: buildah test
on:
  workflow_dispatch:
jobs:
  # ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: buildah unshare ./buildah-test.sh
  #   - run: buildah images
  #   - run: ls -al /var/lib/containers
  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/buildah/stable
      options: --security-opt seccomp=unconfined --security-opt apparmor=unconfined --device /dev/fuse
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p /tmp/storage/overlay-images /tmp/storage/overlay-layers
        touch /tmp/storage/overlay-images/images.lock
        touch /tmp/storage/overlay-layers/layers.lock
        sed -i 's|/var/lib/containers/storage|/tmp/storage|g' /etc/containers/storage.conf
    - name: Cache containers
      uses: actions/cache@v2
      with:
        path: /tmp/storage
        key: ${{ runner.os }}-containers-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-containers-
    - run: buildah unshare ./buildah-test.sh
    - run: buildah images
    - run: ls -al /tmp/storage/overlay-images/

  review:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
    - uses: actions/checkout@v2
    - name: Cache containers
      uses: actions/cache@v2
      with:
        path: /tmp/storage
        key: ${{ runner.os }}-containers-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-containers-
    - run: sudo sed -i 's|/var/lib/containers/storage|/tmp/storage|g' /etc/containers/storage.conf
    - run: buildah images
    - run: ls -al /tmp/storage/overlay-images/
