name: buildah test
on:
  workflow_dispatch:
jobs:
  buildtools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p /tmp/storage/overlay-images /tmp/storage/overlay-layers
        touch /tmp/storage/overlay-images/images.lock
        touch /tmp/storage/overlay-layers/layers.lock
        sed -i 's|/var/lib/containers/storage|/tmp/storage|g' /etc/containers/storage.conf
    - run: |
        podman run --security-opt seccomp=unconfined --security-opt apparmor=unconfined --device /dev/fuse \
        -v "/home/runner/work":"/__w" -v "/tmp/storage:/var/lib/containers/storage" -w "/__w" \
        bash -c "buildah unshare ./buildah-test.sh"
    - run: podman images
