name: Manual workflow
on:
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BTRAY: ${{ secrets.BTRAY }}
      run: buildah unshare ./build.sh
