name: buildah test
on:
  workflow_dispatch:
jobs:
  buildtools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        buildah unshare ./buildah-test.sh
        buildah images
    - run: ls -al /$HOME/.local/share/containers/storage/overlay-images && buildah images && podman images
